### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Timber' not found in /var/www/sitename/web/app/themes/sage-timber-master/index.php on line 10

### ISSUE THREAD

**Issue by Splendorr** [artifex404/sage-timber#4]
Hi! I'm excited to try this theme. However, I can't get it started. I've placed it inside a functioning Bedrock Wordpress installation, alongside a working vanilla Sage installation. I followed the installation instructions, npm install, bower install, all that. When I try to activate the theme, however, I get the following error:

```
Fatal  error: Uncaught Error: Class 'Timber' not found in  /var/www/sitename/web/app/themes/sage-timber-master/index.php  on line 10
--
1 | 0.0003 | 359624 | {main}(  ) | .../index.php:0
2 | 0.0012 | 359912 | require( '/var/www/sitename/web/wp/wp-blog-header.php' ) | .../index.php:5
3 | 0.2349 | 2562520 | require_once( '/var/www/sitename/web/wp/wp-includes/template-loader.php' ) | .../wp-blog-header.php:19
4 | 0.2482 | 2669376 | include( '/var/www/sitename/web/app/themes/sage-timber-master/index.php' ) | .../template-loader.php:74
```

I then tried manually installing Timber with Composer, thinking the theme may not have been able to locate Timber, but that didn't help. I notice that Timber isn't being instantiated anywhere, but following the Timber instructions to initialize it with `$timber = new Timber\Timber();` didn't help; it produced the same error relative to functions.php.

I'm sure I've done something silly, but I can't figure out what it was. Thanks in advance for any help!

**Comment by artifex404** [comment]
If you install Timber with composer, make sure to instantiate it in the theme `functions.php`. See an example here: https://timber.github.io/docs/getting-started/setup/

For an easier start, you could install and activate the Timber plugin: https://wordpress.org/plugins/timber-library/

**Comment by Splendorr** [comment]
@artifex404 Thanks. After installing Timber with Composer, I had tried to initialize it at the bottom of functions.php. Moving it to the top of the file, or to the top of the included lib/timber.php, got things working.

It seems strange to me that this needed to be done manually in an integrated theme, but I suppose you've left it open for people to install Timber by either means? Is there a preferred method of installation?

Either way, thanks for helping me sort out this simple mistake, and thanks for putting the theme together!
