### ISSUE TITLE
Update bower.json to include dependencies

### ISSUE THREAD

**Issue by matriplett** [artifex404/sage-timber#7]
Bower intall gave me errors for missing dependencies for jQuery and popper.js. I corrected this by updating bower.json file to read:

`{
  "name": "sage",
  "homepage": "https://roots.io/sage/",
  "authors": [
    "Ben Word <ben@benword.com>"
  ],
  "license": "MIT",
  "private": true,
  "dependencies": {
    "bootstrap": "git://github.com/twbs/bootstrap.git#v4.0.0",
    "popper.js": "^1.12.3"
  }
}
`

**Comment by artifex404** [comment]
Thanks for the heads up, could you please open up a pull request for the fix?

**Comment by artifex404** [comment]
Bower is a bit of legacy anyways in the theme. I think most people prefer npm over Bower nowadays.

**Comment by artifex404** [comment]
In fact, now that I remember, bootstrap is not included in Bower to be easily installable with npm/yarn.
